name: Metrics
on:
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: a-rustacean
          template: classic
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_timezone: Europe/London
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          repositories_forks: yes
          extras_css: |
            h1, h2, h3 {
              color: #ff76cd;
            }
          extras_js: |
            let days = document.getElementsByClassName("day"); for (let day of days) {if (day.getAttributeNS(null, "fill") == "#ebedf0") {day.setAttributeNS(null, "fill", "#161b22")}}	
          config_order: base.header, base.activity+community, base.repositories, achievements, music, stock, languages
